name: Download SGLang Offline Image

on:
  workflow_dispatch: # 支持在 GitHub Action 页面手动点击按钮触发

jobs:
  build:
    runs-on: ubuntu-latest
    steps:

      - name: Disk Space Reclaimer
        uses: insightsengineering/disk-space-reclaimer@v1.1.2
        with:
          # this might remove tools that are actually needed,
          # if set to "true" but frees about 6 GB
          tools-cache: false

      - name: Pull and Package Images (no gzip)
        run: |
          IMAGES=(
            # "lmsysorg/sglang:latest-cu130-runtime"
            "msysorg/sglang:main-cann9.0.0-a3"
            # "lmsysorg/sglang:latest-cu129-runtime"
          )
          TAR_NAME="sglang-images.tar"

          echo "=========================================="
          echo "1. 开始拉取 SGLang 镜像（共 ${#IMAGES[@]} 个）..."
          echo "=========================================="
          for img in "${IMAGES[@]}"; do
            echo "正在下载: $img ..."
            docker pull "$img"
          done

          echo "=========================================="
          echo "2. 导出为 tar（不压缩）..."
          echo "=========================================="
          docker save "${IMAGES[@]}" -o "$TAR_NAME"

          echo "导出完成，文件大小："
          du -sh "$TAR_NAME"

      - name: 分卷存储（仅切割，不压缩）
        run: |
          # -s 5g 每卷 5GB，-0 表示存储模式（不压缩）
          zip -s 5100m -0 sglang-images.zip sglang-images.tar

      - name: 将每个分卷作为独立 Artifact 上传（官方 gh 命令）
        run: |
          for file in sglang-images.z*; do
            echo "上传 $file ..."
            gh run upload ${{ github.run_id }} "$file" --name "$file"
          done
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}   # 默认就有写入权限

      # - name: 将每个分卷作为独立 Artifact 上传
      #   uses: infogulch/upload-zip-artifacts@v1.0.2
      #   with:
      #     path: "sglang-images.z*"
      # - name: Upload Artifact to GitHub
      #   uses: actions/upload-artifact@v7.0.1
      #   with:
      #     name: sglang-images
      #     path: sglang-images.tar.gz
      #     retention-days: 1 # 在 GitHub 上临时保留 2 天供你点击下载
